### ISSUE TITLE
enable/disable attribute feature

### ISSUE THREAD

**Issue by epcim** [opscode-cookbooks/firewall#59]
Hi, I am considering an usage where 'base' cookbook for the nodes may or may not deploy+enable firewall. As it might be different use-case for different environments.

Then any dependant application cookbook will try to set firewall rules (but only if 'iptables' or 'firewall' cookbook were deployed + enabled. In such case I am missing an general attribute that would handle the 'OS Firewall' state (aka a services should start etc).

Step 1:
on 'base' cookbook the 'firewall cookbook' may or may not bee deployed

Step 2:
on application cookbook
```
if node['firewall']['enabled']
   firewall_rule "http" do
      ...
    end
end
```

Actually, the nice behaviour would be to skip the "if node['firewall'] ... " line and firewall_rule would run it's`action` enable/disable based on the status of the node attribute node['firewall']['enabled'].

That drives the question of best practice. Should the user of this cookbook, introduce attribute such `node['firewall']['enabled']` or  node['MYORG']['firewall_policy']` on it's own in wrapper or no-the-fly and then bind resource attribute parameter `action = node['MYORG']['firewall_policy']`  ?

**Comment by epcim** [comment]
I have just found
```
firewall 'default' do
  action :enable
end
```
which does part of the job. 

Will be the actual state of the firewall stored somewhere? Since if disabled then I guess you still populate the template with rules (which might not be the desired behaviour - like a case the ip tables are not installed yet).

**Comment by martinb3** [comment]
Hi there!

> Will be the actual state of the firewall stored somewhere?

It depends on the distro and which firewall. For distros using firewalld or iptables, there's a separate `:save` action on the firewall resource. For ufw, we currently depend on ufw to preserve the state (which it appears to do automagically).

Hope this helps!

**Comment by epcim** [comment]
Well i understand the point. That fits my requirements. However isn't it a constrain we do not have an node attribute that would return state of the firewall service so the firewall_rule will not run any action if such in disabled?

**Comment by martinb3** [comment]
We've designed the resources and providers in this cookbook, so that, depending on the firewall software (firewalld, iptables, etc), the actual application of firewall rules may happen in firewall or firewall_rule providers. This allows providers to accumulate firewall_rule resources and write one large config, or have each rule manage one firewall rule.

Stated another way, some firewalls can be managed rule by rule, and some cannot be. We designed for both possibilities. Thus, declaring a rule in isolation doesn't always make sense for the data model.

So, the firewall resource is absolutely required, if you supply firewall_rule resources. Ideally, your chef cookbook is idempotent -- it declares a desired state. You could declare a firewall resource with `action :nothing` if you just need the container. That would let you defer the decision until later about whether or not to apply the rules.

I hope this helps.

**Comment by martinb3** [comment]
Hi there! We've refactored master significantly in #84. There is now a disable flag on the firewall resource, that's completely independent of the actions being run on it. The intended state of the firewall is also now stored in a file, especially for firewalls that don't otherwise expose the rules via human-readable file, like ufw.
